version: "2.4"

################################################################################

services:
  gsoc2022:
    hostname: localhost
    runtime: nvidia
    privileged: true
    working_dir: /root/ros_ws
    environment:
      # Pass host user information.
      - HOST_USER=${USER}
      - HOST_UID=1000
      - HOST_GID=1000
      # Display X Server GUI.
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      # Configure Nvidia Docker interface.
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_REQUIRE_CUDA=cuda>=9.0
      - DOCKER_RUNTIME=nvidia
      # Needs to be explicitly define
      - ROS_HOSTNAME=localhost
    image: gsoc2022:latest
    tty: true
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        - DOCKERFILE_COMMIT_SHORT_SHA
    volumes:
      # Map ROS workspace folders.
      - ../panda_dual_arm_demo:/root/ros_ws/src/panda_dual_arm_demo
      - ../moveit:/root/ros_ws/src/moveit
      - ../moveit_msgs:/root/ros_ws/src/moveit_msgs
      - ../moveit_resources:/root/ros_ws/src/moveit_resources
      # Grant display access to X Server.
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    command: tail -f /dev/null

